### ISSUE TITLE
--version returns blank when built from source, version number only supplied in travis build

### ISSUE THREAD

**Issue by chillypepper** [KablamoOSS/kombustion#13]
**Describe the bug**
Running the -v or --version command against kombustion built from the source returns "kombustion version" without a version number, as this version number is supplied as part of the Travis build and so only visible in releases.

**To Reproduce**
1. Build kombustion from source (sh init.sh)
2. Run ./kombustion -v in the project directory
3. You will receive "kombustion version" without a version

**Expected behavior**
A version number should be supplied, eg "kombustion version 0.6.1"

**Additional context**
Given that most people are expected to use the supplied releases and that versioning is handled in part of the build this is unlikely to impact most people, but I think it's worth having a default and consistently valid value returned from this command (as anyone who builds from source is quite likely to use this to test if the build was successful). I'm thinking something like "kombustion version BUILT_FROM_SOURCE", thoughts?

**Comment by ojkelly** [comment]
I think a sane fallback version, if none is supplied is a good way to resolve this.

I'm happy to vote for `BUILT_FROM_SOURCE`

**Comment by ojkelly** [comment]
This was fixed recently in master.
