### ISSUE TITLE
Kombustion should produce an error whenever any of the properties in the resulting template has a null value

### ISSUE THREAD

**Issue by romanrev** [KablamoOSS/kombustion#135]
**Is your feature request related to a problem? Please describe.**
At the moment (v0.4.4) Kombustion does not error whenever it produces a template with any of the properties having a `null` value. It leads to a very cryptic error messages from CloudFormation during the deployment step (such as "Template format error: At least one Resources member must be defined.")

**Describe the solution you'd like**
An error with something like "one of the resources in the resulting template is `null` would be really nice

**Comment by ojkelly** [comment]
Generally `null` values are just removed from the final template. So the bug is possibly around the code that strips them out, and the fact its missing some.
