### ISSUE TITLE
Template format error

### ISSUE THREAD

**Issue by Kablamo-Andrew** [KablamoOSS/kombustion#16]
Error occurring when trying to upsert LoadBalancer Cloud Formation template.

Works fine when upserting with --noBaseOutputs flag.

**Template example**
```
Resources:  
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: "LoadBalancer"
      Scheme: "internal"
      Type: "application"
      Subnets: !Ref Subnets
```

**Error**
```
FATA[0021] ValidationError: Template format error: The Value field of every Outputs member must evaluate to a String.
	status code: 400, request id: 75ac6446-62fd-11e8-b7ae-cfc5ae02eec4 
```

**Comment by iann0036** [comment]
An ELBv2 Load Balancer has a "SecurityGroups" GetAtt return value, however this is not populated when the resource is an NLB or when it is not specified.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#w2ab2c21c10d643c12

Needs thought on how to proceed.

**Comment by iann0036** [comment]
Correction, this may be due to the GetAtt being a list and not a string. The following works:

```  LoadBalancerSecurityGroups:
    Description: LoadBalancer Object
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ElasticLoadBalancingV2LoadBalancer-LoadBalancer-SecurityGroups
    Value:
      Fn::Join:
        - ","
        - Fn::GetAtt:
          - LoadBalancer
          - SecurityGroups
```

Will coordinate an outputs parsers change.
